project:
  type: website
  output-dir: docs

website:
  title: "Data Science Ethics"
  favicon: "images/favicon.ico"
  site-url: https://scolando.github.io/data-science-ethics/
  repo-url: https://github.com/scolando/data-science-ethics
  page-navigation: true
  search:
    type: overlay
    show-item-context: tree
    
  navbar:
    logo: "images/favicon.ico"
    right:
      - text: "Intro to Data Science Ethics"
        menu: 
         - text: "What is Data Science Ethics?"
           href: Intro-DS-ethics.qmd
         - text: "Data Science Lifecycles"
           href: Intro-DS-lifecycle.qmd
      - text: "Inside the Syllabi"
        menu:
         - text: "Data Science Ethics Syllabi"
           href: inside-syllabi.qmd 
         - text: "Most Common Syllabi Topics"
           href: Common-Topics.qmd
         - text: "Data Science Lifecycle Connections"
           href: DS-pipeline.qmd
      - text: "Reading Lists"
        href: Reading-Tags.qmd
    background: white 
    
  page-footer:
    left: "&copy; Copyright 2024, [Sara Colando](https://scolando.github.io/personal-website/) and [Jo Hardin](https://hardin47.netlify.app)"
    
    right:
      - icon: github
        href: https://github.com/scolando/personal-website
    background: white

format:
  html:
    theme:
      - cosmo
      - styles.scss
    backgroundcolor: white

editor: visual
