---
title: "Bias, Fairness, and Justice"
subtitle: "Readings on the normative concepts of bias, fairness, and justice and how they are relevant considerations in data science."
categories:
  - "Interactions with World"
  - "Producing Objects"
  - "Processing Objects as Data"
  - "Ordering Data as Models to Represent the World"
  - "Interpreting Models as Knowledge"
format:
    html:
      citeproc: true
bibliography: bibliographies/Bias.bib
link-citations: true
csl: bibliographies/apa-6th-edition.csl
css: readings.css
---

::: link-2
::: link-2-header
#### {{< iconify icons8:pdf >}} <a href = "pdf-qmds/Bias-pdf.qmd" target = "_blank">Bias, Fairness, and Justice Reading List PDF</a>
:::
:::

| Title                                                                                                      | Citation                |
|------------------------------------------------------------------------------------------------------------|-------------------------|
| Are Algorithms Value-Free?                                                                                 | @Johnson2023            |
| Algorithmic Bias: on the Implicit Biases of Social Technology                                              | @Johnson2020            |
| Algorithmic Bias: Senses, Sources, Solutions                                                               | @FazelpourDanks2021     |
| Fairness                                                                                                   | @vredenburgh2023        |
| Just Machines                                                                                              | @Castro2022             |
| Big Data and Compounding Injustice                                                                         | @Hellman2023            |
| On the Site of Predictive Justice                                                                          | @LazarStoneForthcoming  |
| Proceed with Caution                                                                                       | @ZimmermannStronach2021 |
| Semantics Derived Automatically from Language Corpora Contain Human-like Biases                            | @Caliskan2017           |
| The Algorithmic Leviathan: Arbitrariness, Fairness, and Opportunity in Algorithmic Decision-Making Systems | @CreelHellamn2022       |
| Facebook has been Charged with Housing Discrimination by the US government                                 |                         |

## References

::: {#refs}
:::
